/* Generated By:JavaCC: Do not edit this line. PDDL30parserConstants.java */
package javaff.parser.parser30;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PDDL30parserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPEN = 5;
  /** RegularExpression Id. */
  int CLOSE = 6;
  /** RegularExpression Id. */
  int DEFINE = 7;
  /** RegularExpression Id. */
  int DOMAIN = 8;
  /** RegularExpression Id. */
  int DOMAIN_LABEL = 9;
  /** RegularExpression Id. */
  int OBJECTS = 10;
  /** RegularExpression Id. */
  int GOAL = 11;
  /** RegularExpression Id. */
  int INIT = 12;
  /** RegularExpression Id. */
  int METRIC = 13;
  /** RegularExpression Id. */
  int CONSTRAINTS = 14;
  /** RegularExpression Id. */
  int PREFERENCE = 15;
  /** RegularExpression Id. */
  int PROBLEM = 16;
  /** RegularExpression Id. */
  int REQUIREMENTS = 17;
  /** RegularExpression Id. */
  int REQUIREMENT_LABELS = 18;
  /** RegularExpression Id. */
  int NON_HANDLED_LABELS = 19;
  /** RegularExpression Id. */
  int TYPES = 20;
  /** RegularExpression Id. */
  int EITHER = 21;
  /** RegularExpression Id. */
  int CONSTANTS = 22;
  /** RegularExpression Id. */
  int PREDICATES = 23;
  /** RegularExpression Id. */
  int FUNCTIONS = 24;
  /** RegularExpression Id. */
  int ACTION = 25;
  /** RegularExpression Id. */
  int DURATIVE_ACTION = 26;
  /** RegularExpression Id. */
  int PARAMETERS = 27;
  /** RegularExpression Id. */
  int DURATION = 28;
  /** RegularExpression Id. */
  int DUR_VAR = 29;
  /** RegularExpression Id. */
  int PRECONDITION = 30;
  /** RegularExpression Id. */
  int CONDITION = 31;
  /** RegularExpression Id. */
  int EFFECT = 32;
  /** RegularExpression Id. */
  int AND = 33;
  /** RegularExpression Id. */
  int NOT = 34;
  /** RegularExpression Id. */
  int OVER_ALL = 35;
  /** RegularExpression Id. */
  int AT_START = 36;
  /** RegularExpression Id. */
  int AT_END = 37;
  /** RegularExpression Id. */
  int EQUALS = 38;
  /** RegularExpression Id. */
  int TYPE_IDENT = 39;
  /** RegularExpression Id. */
  int BINARY_OP = 40;
  /** RegularExpression Id. */
  int BINARY_COMP = 41;
  /** RegularExpression Id. */
  int ASSIGN_OP = 42;
  /** RegularExpression Id. */
  int ASSIGN = 43;
  /** RegularExpression Id. */
  int SCALE_UP = 44;
  /** RegularExpression Id. */
  int SCALE_DOWN = 45;
  /** RegularExpression Id. */
  int INCREASE = 46;
  /** RegularExpression Id. */
  int DECREASE = 47;
  /** RegularExpression Id. */
  int OPTIMIZATION = 48;
  /** RegularExpression Id. */
  int MINIMIZE = 49;
  /** RegularExpression Id. */
  int MAXIMIZE = 50;
  /** RegularExpression Id. */
  int TOTAL_TIME = 51;
  /** RegularExpression Id. */
  int VAR = 52;
  /** RegularExpression Id. */
  int ALWAYS = 53;
  /** RegularExpression Id. */
  int SOMETIME = 54;
  /** RegularExpression Id. */
  int WITHIN = 55;
  /** RegularExpression Id. */
  int AT_MOST_ONCE = 56;
  /** RegularExpression Id. */
  int SOMETIME_AFTER = 57;
  /** RegularExpression Id. */
  int SOMETIME_BEFORE = 58;
  /** RegularExpression Id. */
  int ALWAYS_WITHIN = 59;
  /** RegularExpression Id. */
  int HOLD_DURING = 60;
  /** RegularExpression Id. */
  int HOLD_AFTER = 61;
  /** RegularExpression Id. */
  int NUMBER = 62;
  /** RegularExpression Id. */
  int NAME = 63;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 64;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\"define\"",
    "\"domain\"",
    "\":domain\"",
    "\":objects\"",
    "\":goal\"",
    "\":init\"",
    "\":metric\"",
    "\":constraints\"",
    "\"preference\"",
    "\"problem\"",
    "\":requirements\"",
    "<REQUIREMENT_LABELS>",
    "<NON_HANDLED_LABELS>",
    "\":types\"",
    "\"either\"",
    "\":constants\"",
    "\":predicates\"",
    "\":functions\"",
    "\":action\"",
    "\":durative-action\"",
    "\":parameters\"",
    "\":duration\"",
    "\"?duration\"",
    "\":precondition\"",
    "\":condition\"",
    "\":effect\"",
    "\"and\"",
    "\"not\"",
    "\"over all\"",
    "\"at start\"",
    "\"at end\"",
    "\"=\"",
    "\"-\"",
    "<BINARY_OP>",
    "<BINARY_COMP>",
    "<ASSIGN_OP>",
    "\"assign\"",
    "\"scale-up\"",
    "\"scale-down\"",
    "\"increase\"",
    "\"decrease\"",
    "<OPTIMIZATION>",
    "\"minimize\"",
    "\"maximize\"",
    "\"total-time\"",
    "<VAR>",
    "\"always\"",
    "\"sometime\"",
    "\"within\"",
    "\"at-most-once\"",
    "\"sometime-after\"",
    "\"sometime-before\"",
    "\"always-within\"",
    "\"hold-during\"",
    "\"hold-after\"",
    "<NUMBER>",
    "<NAME>",
    "<SINGLE_LINE_COMMENT>",
  };

}
